/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistroIndexRouteImport } from './routes/registro/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as MisEventosIndexRouteImport } from './routes/mis-eventos/index'
import { Route as MapaIndexRouteImport } from './routes/mapa/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CrearEventoIndexRouteImport } from './routes/crear-evento/index'
import { Route as PerfilesProfileIdRouteImport } from './routes/perfiles/$profileId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EventsEventIdEditarIndexRouteImport } from './routes/events/$eventId/editar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroIndexRoute = RegistroIndexRouteImport.update({
  id: '/registro/',
  path: '/registro/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisEventosIndexRoute = MisEventosIndexRouteImport.update({
  id: '/mis-eventos/',
  path: '/mis-eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaIndexRoute = MapaIndexRouteImport.update({
  id: '/mapa/',
  path: '/mapa/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearEventoIndexRoute = CrearEventoIndexRouteImport.update({
  id: '/crear-evento/',
  path: '/crear-evento/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesProfileIdRoute = PerfilesProfileIdRouteImport.update({
  id: '/perfiles/$profileId',
  path: '/perfiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditarIndexRoute =
  EventsEventIdEditarIndexRouteImport.update({
    id: '/editar/',
    path: '/editar/',
    getParentRoute: () => EventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/crear-evento/': typeof CrearEventoIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/mapa/': typeof MapaIndexRoute
  '/mis-eventos/': typeof MisEventosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/registro/': typeof RegistroIndexRoute
  '/events/$eventId/editar/': typeof EventsEventIdEditarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/crear-evento': typeof CrearEventoIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/mapa': typeof MapaIndexRoute
  '/mis-eventos': typeof MisEventosIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/registro': typeof RegistroIndexRoute
  '/events/$eventId/editar': typeof EventsEventIdEditarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/crear-evento/': typeof CrearEventoIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/mapa/': typeof MapaIndexRoute
  '/mis-eventos/': typeof MisEventosIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/registro/': typeof RegistroIndexRoute
  '/events/$eventId/editar/': typeof EventsEventIdEditarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/perfiles/$profileId'
    | '/crear-evento/'
    | '/dashboard/'
    | '/login/'
    | '/mapa/'
    | '/mis-eventos/'
    | '/perfil/'
    | '/registro/'
    | '/events/$eventId/editar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/perfiles/$profileId'
    | '/crear-evento'
    | '/dashboard'
    | '/login'
    | '/mapa'
    | '/mis-eventos'
    | '/perfil'
    | '/registro'
    | '/events/$eventId/editar'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/perfiles/$profileId'
    | '/crear-evento/'
    | '/dashboard/'
    | '/login/'
    | '/mapa/'
    | '/mis-eventos/'
    | '/perfil/'
    | '/registro/'
    | '/events/$eventId/editar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  PerfilesProfileIdRoute: typeof PerfilesProfileIdRoute
  CrearEventoIndexRoute: typeof CrearEventoIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MapaIndexRoute: typeof MapaIndexRoute
  MisEventosIndexRoute: typeof MisEventosIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  RegistroIndexRoute: typeof RegistroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro/': {
      id: '/registro/'
      path: '/registro'
      fullPath: '/registro/'
      preLoaderRoute: typeof RegistroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-eventos/': {
      id: '/mis-eventos/'
      path: '/mis-eventos'
      fullPath: '/mis-eventos/'
      preLoaderRoute: typeof MisEventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa/': {
      id: '/mapa/'
      path: '/mapa'
      fullPath: '/mapa/'
      preLoaderRoute: typeof MapaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-evento/': {
      id: '/crear-evento/'
      path: '/crear-evento'
      fullPath: '/crear-evento/'
      preLoaderRoute: typeof CrearEventoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles/$profileId': {
      id: '/perfiles/$profileId'
      path: '/perfiles/$profileId'
      fullPath: '/perfiles/$profileId'
      preLoaderRoute: typeof PerfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/editar/': {
      id: '/events/$eventId/editar/'
      path: '/editar'
      fullPath: '/events/$eventId/editar/'
      preLoaderRoute: typeof EventsEventIdEditarIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdEditarIndexRoute: typeof EventsEventIdEditarIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdEditarIndexRoute: EventsEventIdEditarIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  PerfilesProfileIdRoute: PerfilesProfileIdRoute,
  CrearEventoIndexRoute: CrearEventoIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MapaIndexRoute: MapaIndexRoute,
  MisEventosIndexRoute: MisEventosIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  RegistroIndexRoute: RegistroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
